package demo.rpc.jws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebService(name = "helloService", targetNamespace = "http://demo.rpc/jws/server")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloService {

    /**
     * 
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://demo.rpc/jws/server/helloService/sayHelloRequest",
            output = "http://demo.rpc/jws/server/helloService/sayHelloResponse")
    public String sayHello(@WebParam(name = "arg0", partName = "arg0") String arg0);

}
